apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
  labels:
    app: service-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-test
  template:
    metadata:
      labels:
        app: service-test
    spec:
      containers:
        - name: demo
          image: victorf13/service-test:2431040
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
